# .github/workflows/ci.yml

name: CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: translation
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: changeme
        ports:
          # Questa riga mappa la porta 5432 del DB alla porta 5432 della macchina HOST
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
          
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Wait for PostgreSQL and Debug Network
        run: |
          echo "Waiting 10 seconds for network to stabilize..."
          sleep 10
          echo "--- Network Status (netstat) ---"
          netstat -tuln
          echo "--- Hosts File (etc/hosts) ---"
          cat /etc/hosts
          
      - name: Run migrations
        env:
          # STRATEGIA FINALE: Usiamo l'IP esplicito 127.0.0.1 (localhost dell'host)
          DATABASE_URL: postgres://postgres:changeme@127.0.0.1:5432/translation
        run: python manage.py migrate
        
      - name: Run tests
        env:
          # La stessa URL esplicita anche per i test
          DATABASE_URL: postgres://postgres:changeme@127.0.0.1:5432/translation
        run: pytest --maxfail=1 --disable-warnings -q